version: 2.1

executors:
  base:
    docker:
      - image: circleci/php:7.3
        environment:
          VVV_PATH_TO_SITE: /home/circleci/project
          VVV_SITE_NAME: test-provisioning
          DB_NAME: test-provisioning
          project: test-provisioning
          DB_PREFIX: ds_wp_
          DOMAIN: test-provisioning.test
          PUBLIC_DIR: public_html
          SITE_TITLE: test-provisioning.test
          WP_LOCALE: fr_FR
          WP_TYPE: single
          WP_VERSION: latest

      # Service container image available at `host: localhost`

      - image: circleci/mysql:5.7-ram
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test-provisioning
          MYSQL_USER: wp
          MYSQL_PASSWORD: wp
commands:
  setup_environment:
    steps:
      - run:
          name: Add deploy host to known_hosts
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            if [ -v PRIV_KEY ]; then echo "$PRIV_KEY" | base64 --decode > /tmp/my.key && chmod 400 /tmp/my.key && ssh-add -k /tmp/my.key; fi

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install mysqli
      - run: sudo apt-get install default-mysql-client
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get install default-mysql-client
      - run:
          name: Install WP-CLI
          command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
            which wp
jobs:
  provision_without_db_restore:
    description: Provisions wordpress and starter theme
    executor: base
    steps:
      - checkout
      - setup_environment
      - run:
          name: Provision script
          command: |
            source ./.circleci/provision-helpers.sh
            bash provision/vvv-init.sh
  provision_with_db_restore:
    description: Provisions wordpress and starter theme
    executor: base
    steps:
      - checkout
      - setup_environment
      - run:
          name: Copy dummy database backup
          command: sudo mkdir -p /srv/database/backups && cp .circleci/test-provisioning.sql /srv/database/backups/test-provisioning.sql
      - run:
          name: Provision script
          command: |
            source ./.circleci/provision-helpers.sh
            bash provision/vvv-init.sh
workflows:
  install_new_site:
    jobs:
      - provision_without_db_restore
      - provision_with_db_restore
